# Generated by Django 5.2 on 2025-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('video_title', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('video_url', models.URLField()),
                ('video_thumbnail', models.URLField()),
            ],
        ),
    ]
