# Generated by Django 5.0.6 on 2025-06-11 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlist_id_alter_playlistitem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
