from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PlaylistViewSet, PlaylistRetrieveUpdateDestroyAPIView, PlaylistListCreateAPIView, AddVideoToPlaylistAPIView, PlaylistItemDestroyAPIView, PlaylistReorderItemsAPIView

router = DefaultRouter()
router.register(r'playlists', PlaylistViewSet, basename='playlist')

urlpatterns = [
    path('', include(router.urls)),


# URLs generated by router will include:
# /playlists/ (list, create)
# /playlists/{id}/ (retrieve, update, delete)
# /playlists/{id}/share/ (custom action)
    path('', include(router.urls)),
    path('playlists/', PlaylistListCreateAPIView.as_view(), name='playlist-list-create'),
    path('playlists/<uuid:pk>/', PlaylistRetrieveUpdateDestroyAPIView.as_view(), name='playlist-detail'), 
    path('playlists/<uuid:playlist_pk>/items/', AddVideoToPlaylistAPIView.as_view(), name='playlist-add-item'),
    path('playlists/<uuid:playlist_pk>/items/<int:item_pk>/', PlaylistItemDestroyAPIView.as_view(), name='playlist-remove-item'),
    path('playlists/<uuid:playlist_pk>/reorder-items/', PlaylistReorderItemsAPIView.as_view(), name='playlist-reorder-items'),
]

# URLs generated by router will include:
# /playlists/ (list, create)
# /playlists/{id}/ (retrieve, update, delete)
# /playlists/{id}/share/ (custom action)
